### ISSUE TITLE
[Feature Request] Ignore specific files

### ISSUE THREAD

**Issue by boka18** [dkfbasel/hot-reload#9] opened 2022-02-16 13:17 UTC
Currently we can only ignore specific directories. Is it possible to do the same for files?
For example: I want to ignore a file that is on the root of my project. 

Thanks!

**Comment by tikiatua** [comment] 2022-02-16 16:13
Hi @boka18 
Thank you for your message. This is currently not possible, but I should be able to easily add this. I will get back to you on this in a few hours.

**Comment by boka18** [comment] 2022-02-16 17:38
That was fast! 🚀

**Comment by tikiatua** [comment] 2022-02-16 21:20
Updated version 1.17.7 is now available. Allows to ignore specific files, you can even use glob pattern matching to specify which files to ignore, i.e. ignore=/subdir,*.md,*.txt

While writing this, it occurred to me, that we could even only include .go files in the watcher. This would avoid triggering rebuilds when other files are edited.

What do you think? Would this be something that you expect, or is it better to watch all files unless specifically ignored?

**Comment by boka18** [comment] 2022-02-17 12:12
Love the thinking.

I think it's fair to ignore all .log files out of the box. I can't think of any case where the end user would like a refresh on .log change. That was my original issue.

That said, maybe add `**.log` files to be ignored in the `docker-compose.yml@IGNORE` param and leave all the freedom of ignoring specific files to the user.

**Comment by boka18** [comment] 2022-03-01 17:10
Closing this since the requested feature was implemented. Thanks @tikiatua

**Comment by boka18** [comment] 2022-03-01 17:19
Reopening this.
looks like this is not working as expected.

What I did:
updated my docker-compose.yml ignore param to:
```yaml
    ...
    environment:
      # directory to look for the main go entry point (default: /app)
      - DIRECTORY=/app
      # specify the command that should be run, can be 'build' or 'test'
      # 'build' is the default command 
      - CMD=build
      # arguments can be used to specify arguments to pass to the executable
      # on running
      - ARGS=-test=someString
      # ignore will indicate which subdirectories to ignore from watching
      - IGNORE=*.xlsx,*.log
```

But whenever the .log file gets updated, the go service reloads. Please advise

**Comment by tikiatua** [comment] 2022-03-02 11:11
Hi @boka18 

Thank you for your feedback. The issue is due to the way the matching for ignore files works. Internally we use filepath.Match to determine if a file or folder should be exluded. filepath.Match must match the complete filepath to have a successful match.

I will probably need to switch to a different match method to solve the issue.

**Comment by tikiatua** [comment] 2022-03-02 11:34
It should be fixed now. I changed the matcher library to github.com/becheran/wildmatch-go. This supports a pattern matching which is probably more in line with what users would expect.

Please use `docker pull dkfbasel/hot-reload-go:1.17.7` to get the newest version of the container.

**Comment by boka18** [comment] 2022-03-02 13:26
thanks for the fast patch @tikiatua!
Works as expected now! Feel free to close the issue if there's nothing left to discuss.

Edit:
@tikiatua Actually, the reload doesn't work at all now...

**Comment by tikiatua** [comment] 2022-03-18 15:31
Could you please check again with the new version 1.18.0 (dkfbasel/hot-reload-go:1.18.0). The code in the test directory works as expected on my system. Please provide me with some more information from your docker-compose.yml if it still does not work for you.

**Comment by boka18** [comment] 2022-03-21 14:58
looks like it's working as expected now! Thanks again! 👏 

Feel free to close the issue if you don't need anymore info or testing

**Closed as completed** 2022-03-24 20:57 UTC
